clar-test/clar

clar.c

When the `-v` flag is provided on the command-line, increase
verbosity of output.  Presently, this means printing suite names
during execution.
This can aide in quickly identifying test failures or skipped tests when you have a large number of tests to execute.

Introduce verbosity with the `-v` flag

---

clar.c
clar.h

This commit adds a hook to let the test application to request trace events when suites and tests are started and finished.
This can be used by the application to write log/trace messages to the same log stream used by their actual tests.
I have an demonstration in https://github.com/jeffhostetler/public_libgit2 in branch jeffhostetler/wip/clar_trace2

Add trace hook to clar

---

clar.c

If I have some tests disabled by default (say, the `online` tests), and run `clar -sonline::clone`, then I expect it to run only `online::clone`.  Since those are disabled though, it falls out of that and runs everything.

Make '-s' imply '-i'

---

clar/fixtures.h

Support hierarchical test resource data, such that you can have
`tests/resources/foo/bar` and move the `bar` directory in as
a fixture.
Calling `cl_fixture_sandbox` on a path that is not directly beneath
the test resources directory succeeds, placing that directory into
the test fixture.  (For example, `cl_fixture_sandbox("foo/bar")`
will sandbox the `foo/bar` directory as `bar`).
Add support for cleaning up directories created this way, by only
cleaning up the basename (in this example, `bar`) from the fixture
directory.

support hierarchical test resource data

---

clar/sandbox.h

Some compilers are getting whiny about ignoring the return code.

sandbox: check chdir return code

---

clar.c

When passing in a specific suite which should be executed by clar
via `-stest::suite`, we try to parse this string and then include
all tests contained in this suite. This also includes all tests
in sub-suites, e.g. 'test::suite::foo'.
In the case where multiple suites start with the same _string_,
for example 'test::foo' and 'test::foobar', we fail to
distinguish this correctly. When passing in `-stest::foobar`,
we wrongly determine that 'test::foo' is a prefix and try to
execute all of its matching functions. But as no function
will now match 'test::foobar', we simply execute nothing.
To fix this, we instead have to check if the prefix is an actual
suite prefix as opposed to a simple string prefix. We do so by by
inspecting if the first two characters trailing the prefix are
our suite …

Fix parsing of test suite prefixes

---

generate.py

TL;DR:
'generate.py' fails to generate tests on file with mtime=0:
```
$ touch --date=@0 clar.{c,h}
$ python generate.py
Traceback (most recent call last):
File "generate.py", line 242, in <module>
if suite.write():
File "generate.py", line 211, in write
data.write(t.render())
File "generate.py", line 25, in render
out = "\n".join("extern %s;" % cb['declaration'] for cb in self.module.callbacks) + "\n"
AttributeError: 'Module' object has no attribute 'callbacks'
```
Long story:
Error happens because 'generate.py' uses '0' as a sentinel value.
In order to enhance reproducibility of builds some build systems
timestamps to a stable date (say, release tarball date).
https://www.gnu.org/software/guix/ goes even farther that that
and sets mtime to '0'. Unfortunately it is exactly the same as …

generate.py: don't skip files with mtime = 0

---

clar/print.h

motivation: (for someone new to the tests) it's puzzling to find the odd 'S' interspersed in the test output
proposed alternative test output (extract):
$ cmake --build . && ./libgit2_clar -srepo -v
...
Loaded 340 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
repo::config...
repo::discover..........
repo::env.
repo::getters...
repo::hashfile..
repo::head......................
repo::headtree....
repo::init.........................S
repo::message..
repo::new..
repo::open.............
repo::pathspec..........
repo::reservedname.....
repo::setters.....
repo::shallow....
repo::state.............

add test status codes legend to the 'Started' test trace

---

clar.c
clar.h
clar/fixtures.h
clar/print.h
clar/sandbox.h
clar/summary.h
generate.py

This is an attempt at consolidating changes made to `libgit2`'s clar somewhere, I'm filing it mostly for reference and to have the list handy (I had started a few month ago, but the recent discussion spurred me to finish it). Changes might have been applied in a different order though.
Copying the current clar files from `libgit2` on top of this will result in this diff, so I think I missed a commit somewhere :
```diff
diff --git i/generate.py w/generate.py
index 993fb274e..572a57f86 100755
--- i/generate.py
+++ w/generate.py
@@ -76,7 +76,7 @@ def render(self):
def __init__(self, name):
self.name = name
-        self.mtime = None
+        self.mtime = 0
self.enabled = True
self.modified = False
@@ -222,16 +222,18 @@ def write(self):
return False
with open(output, 'w') as data:
- …
```

Consolidate libgit2 changes

---

generate.py

Failing to do that makes clar miss the last of the suites, as all duplicated "data" would have not been accounted for.

Correctly account for "duplicated" suites when counting

---

clar/fs.h

clar has historically shelled out to `/bin/cp` to copy test fixtures into a sandbox and `/bin/rm` to clean them up.  This has two deficiencies:
1. `/bin/cp` is slower than simply opening the source and destination and copying them in a read/write loop.  On my Mac, the `/bin/cp` based approach takes ~2:40 for a full test pass.  Using a read/write loop to copy the files ourselves takes ~1:50.  Similarly, `/bin/rm` is slower than doing this internally.  Moving to an internal traversal shaves another 20 seconds off.
These numbers are less impressive on Linux, but using `sendfile` there makes a notable improvement.
2. It's noisy.  Since the leak detector follows fork/exec, we'll end up running the leak detector on `/bin/cp` and `/bin/rm`.  This would be fine, except that the leak detector …

use internal functions instead of /bin/cp and /bin/rm

---

clar.c

When using `-s` to specify a particular test, it will do a prefix match.
Thus, `-sapply::both::rename_a_to_b_to_c` will match both a test named `test_apply_both__rename_a_to_b_to_c` and a test that begins with that name, like `test_apply_both__rename_a_to_b_to_c_exact`.
Permit a trailing `$` to `-s` syntax.  This allows a user to specify `-sapply::both::rename_a_to_b_to_c$` to match _only_ the `test_apply_both__rename_a_to_b_to_c` function.
We already filter to ensure that the given prefix matches the current test name.  Also ensure that the length of the test name matches the length of the filter, sans trailing `$`.

offer exact name matching with a `$` suffix

---

clar.c
clar.h
clar/print.h

This adds a new command-line option to clar, `-t`, which will produce output in the popular TAP format, which can be used by multiple different frontends to display test output.
This retroactively names the existing clar output format as "clap" (the "clar protocol"), and adds support for tap (the [test anywhere protocol](https://testanything.org/)).
This adds support for [TAP version 13](https://testanything.org/tap-version-13-specification.html).
It includes the optional YAML block to provide more information about test failures.  Since this is not yet standardized, we have copied the output format of the popular [node tap](https://node-tap.org/tap-protocol).
Fixes #38

TAP style output

---

clar/fs.h
clar/sandbox.h

This change makes it possible to build with newer versions of gcc
without warnings. There were two warnings issued:
* gcc 8 added
[`-Wstringop-truncation`](https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/),
which warns if a call to `strncpy(3)` is prone to accidentally
truncating the destination string, since `strncpy(3)` does NOT add a
terminating `NULL` if the destination buffer is not large enough to
hold the input.
This change uses the pattern suggested in
https://us-cert.cisa.gov/bsi/articles/knowledge/coding-practices/strncpy-and-strncat
to fix the locations flagged by gcc.
* There was a potentially uninitialized access of `dest` in `fs_copy`.
From https://github.com/libgit2/libgit2/pull/5749

Fix the `-DENABLE_WERROR=ON` build for gcc 10.2

---

clar/fs.h

When `CLAR_WIN32_LONGPATHS` is defined, we will use the `\\?\` syntax to support paths longer than 260 characters.

win32: support long paths (optionally)

---

clar.c
clar/fixtures.h
clar/fs.h

Avoid unused function warnings for users who do not have fixtures.

Only compile fixture functions when functions exist

---

clar/fs.h
clar/sandbox.h
generate.py
test/.gitignore

There are multiple places with broken whitespace formatting as pointed out by git-apply(1). Fix these to make the command happy.

global: fix whitespace errors

---

clar.c
clar/fs.h
clar/sandbox.h

Fix a couple of platform compatibility issues with MinGW and HPE NonStop. These patches are required by Git to make the clar work for all currently tested platforms.
The HPE NonStop changes have been picked from https://github.com/clar-test/clar/pull/96, removing the other changes to make the CFLAGS overridable. The Windows fixes have been picked from the [downstream patch series in Git](https://lore.kernel.org/git/cover.1722415748.git.ps@pks.im/T/#meee619275b1c92f7966e65ce29969817e539e171).
The patches were originally by @rsbeckerca and @dscho. I have noted authorship via `Original-patch-by` trailers, but am happy to attribute full authorship of the commits if preferred by the authors.

Platform compatibility with MinGW and HPE NonStop

---

clar.c
clar/print.h
clar/sandbox.h
clar/summary.h

Failures are being treated somewhat inconsistently throughout the clar codebase. Introduce a new function `clar_abort()` and adapt our error handling to use it consistently.

Handle failures more consistently via `clar_abort()`

---

clar.c

The Windows platform has multiple different definitions for stat(3P) and its `struct stat` with different integer widths for both the filesize and the timestamps. For our usecase, we really only need to care whether we end up using `_stat()` or `stat()`, which require us to use either `struct _stat` or `struct stat`, respectively.
The way we handle this in "clar.c" is somewhat convoluted though because we select the function and structure to use independently of each other. This can cause us to pick the wrong combination of features in some environments, like mingw-w64.
Simplify the code such both function and struct get set up under the same condition such that this cannot happen anymore.

clar: simplify how we handle stat(3P) on Win32

---

clar.c
test/CMakeLists.txt

Compiling clar requires several different extensions which are not part
of ISO C90, like strdup(3P), lstat(3P) and mkdtemp(3P). And while we
define these via our CMake build instructions, downstream users do not
benefit from this and will have to make sure that they set these.
Let's instead pull the definitions into "clar.c" such that the macros
are defined for everyone.

clar: define feature macros in "clar.c"

---

clar.c
clar/sandbox.h

The clar does not compile on SunOS because it does not support POSIX.1-2008. This PR makes things work on that platform.

SunOS compatibility

---

clar.c

Some implementations of libc do not have proper support for `wchar_t`. One such library is uClibc, which only has optional support for this type. When not enabled, then the <wchar.h> header will be a mere stub that only contains a typedef for `wchar_t`, but nothing else.
Drop our use of `wchar_t` on such platforms.

clar: support compilation without support for `wchar_t`

---

.github/workflows/ci.yml
clar.c

Plug memory leaks and detect them as part of our CI.
Depends on #102.

Memory leak fixes

---

clar/print.h

When operating in `-v -v` mode, the "skipped" tests do not emit a newline in the report.

clar: emit newline on status

---

clar.c

* Ensure that arguments (like `-v`) do not have trailing characters.
* Allow suites to be a separate argument (eg `-s online`, not just `-sonline`).

clar: argument parsing improvements

---

README.md
clar.c
clar.h
test/selftest.c

When invoking a helper function (or "auxiliary method", in the documentation), we lose the file/function/line information of the current call point. This means that we attribute failures to the helper function instead of the actual test.
Provide a `cl_invoke` function that will preserve the current state. This allows callers to use the simpler "clar style" as documented, but get the correct failure location.

invoke: preserve line numbers during helper methods

---

.github/workflows/ci.yml
clar.c
clar.h
clar/fixtures.h
clar/fs.h
clar/sandbox.h

Some changes to temporary directory handling — general quality-of-life changes with an eye toward eventually supporting parallel execution (presumably with separate tempdirs per thread).
* canonicalize temp sandbox directory everywhere
We currently only canonicalize the temp sandbox directory on macOS,
which is critical since `/tmp` is really `/private/tmp`. However, we
should do it everywhere, so that tests can actually expect a consistent
outcome by looking at `clar_sandbox_path()`.
* tempdir and sandboxes are now separate entities
clar now has the concept of a _temporary directory_, which is the
temporary directory for the entirety of a `clar` invocation (a set of
test runs) and a sandbox, which is the temporary directory for a single
test invocation.
This allows us to ensure that a …

Some temporary directory handling changes

---

CMakeLists.txt
clar/sandbox.h

Given that test names can be long _and_ some platforms insist upon a
short maximum path length (eg, Windows), we may not want to
indiscriminately use path names as the sandbox directory name.
However, this has high utility in some situations, so allow it as an
opt-in. By default, we'll just use an 8 hexadigit "random" string.
(We'll use the rand(3) mechanism, which is not be particularly random,
but since the sandbox directories are sequestered in a unique tempdir,
a clar process need only attempt to avoid collisions between itself,
not with other processes.)

Use random sandbox names (by default)

---

clar.c
clar/summary.h

I am playing around with static analyzers, and the first one complained about these two issues, which are easily fixed.

Some fixes

---

clar.c
clar/print.h
test/expected/help
test/expected/quiet

The quiet mode activated via "-q" is quite broken:
- We print all failures twice with clap formatting, so we effectively increase verbosity.
- We don't print individual test status indicators ("...FF..F"), but print the legend to explain what the symbols mean.
- We don't print any "ok/not ok" lines at all with TAP formatting, which breaks the specification.
This PR fixes all of those issues.

Fix formatting in quiet mode

---

clar.c

When building with -Og and -Wmaybe-uninitialized on gcc 15.1.1, the build produces a warning. In practice, though, this cannot be hit because `exact` acts as a guard and that variable can only be set after `matchlen` is already initialized
Assign a default value to `matchlen` so that the warning is silenced.
This patch is taken from [0].
[0]: https://github.com/git/git/commit/3a7e783d9c5334cc5ea1af74b42297560ce697ce

clar.c: fix -Wmaybe-uninitialized with -Og

---

clar.c

It was reported that `uintptr_t` is not available on some platforms like NonStop. Work around this limitation by using `uintmax_t` instead.

clar: remove unportable use of `uintptr_t`
